image: docker.flyingflip.com/probo/ubuntu:20.04-php8.0
steps:
  - name: Set up our LAMP Plugin
    plugin: LAMPApp
  - name: Basic Information Page
    command: 'mv $SRC_DIR/src /var/www/html'
  - name: Versionizer output
    command: versionizer
