image: proboci/alpine:php8.4
steps:
  - name: Set up our Testinig LAMP Plugin Environment
    plugin: LAMPApp
    phpIniOptions:
      memory_limit: 512M
      max_execution_time: 300
    subDirectory: src
  - name: Versionizer output
    command: versionizer
    
