image: proboci/ubuntu:18.04-php8.0
steps:
  - name: Download a fresh copy of Backdrop CMS
    command: bee -y download-core /src && cd /src && chmod -R 777 *

  - name: Create A Base Backdrop Site
    plugin: Backdrop
    runInstall: true
    installArgs: --username=admin --password=Welcome12345 --site-name="Backdrop Development" --auto
    subDirectory: ''

  - name: Install Entity Modules for OG
    command: bee -y --root=/src download entity_plus entity_ui entityreference

  - name: Enable modules
    command: bee -y --root=/src enable entity_plus entity_ui entityreference

  - name: Get Organic Groups
    command: wget https://github.com/backdrop-contrib/og/archive/refs/heads/1.x-2.x.zip && unzip 1.x-2.x.zip && mv og-1.x-2.x /src/modules/og

  - name: Enable Organic Groups
    command: bee -y --root=/src enable og og_access og_context og_field_access og_register og_ui

  - name: Fix files directory permissions due to og install
    command: chown -R www-data:www-data /src
