image: proboci/ubuntu:22.04-php8.1
steps:
  - name: Install Drupal Files From Composer
    plugin: Script
    script: |
      cd /src
      composer create-project drupal/recommended-project drupal
      cd drupal/web
      composer require drush/drush
  - name: Setup Drupal Plugin
    plugin: Drupal
    clearCaches: false
    subDirectory: drupal/web
    databaseUpdates: false
    drupalVersion: 10
    configSyncDirectory: ../config/sync
    phpIniOptions:
      upload_max_filesize: 50M
      post_max_size: 25M
      memory_limit: 512M
  - name: Install Drupal
    plugin: Script
    script: |
      drush -r /var/www/html site:install -y \
      --db-url=mysql://root:strongpassword@localhost/drupal \
      --account-name=admin \
      --account-pass=password \
      --account-mail=mbagnall@gmail.com \
      --site-mail=mbagnall@gmail.com \
      --site-name="Probo"
  - name: Drush test
    plugin: Script
    script: |
      drush status
      drush updb
      drush cr
      drush cex

