image: proboci/ubuntu:18.04-php7.4
#notifications:
#  webhook: https://admin.powertools.sh/api/probo/v1/webhook
steps:
  - name: Basic Information Page
    command: 'mv $SRC_DIR/docroot /var/www/html'
