image: proboci/alpine:php8.3
steps:
  - name: Set up our LAMP Plugin
    plugin: LAMPApp
    phpIniOptions:

      memory_limit: 512M
      max_execution_time: 300
    subDirectory: src
  - name: Basic Information Page
    command: 'mv $SRC_DIR/src /var/www/html'
  - name: Versionizer output
    command: versionizer
    
