image: proboci/alpine:php8.0

steps:
  - name: Drupal 9 Files From Drupal.org
    plugin: Script
    script: |
      rm -rf /var/www/html
      cd $SRC_DIR
      composer create-project drupal/recommended-project docroot
      cd /src/docroot
      composer require drush/drush drupal/admin_toolbar drupal/search_api drupal/search_api_solr drupal/module_filter
      chmod -R 777 /src/docroot/web/sites/default

  - name: Set Up Database For Drupal 9
    plugin: Drupal
    drupalVersion: 9
    subDirectory: docroot/web
    phpIniOptions:
      memory_limit: 512M

  - name: Run the Drupal 9 Site Installation
    plugin: Script
    script: |
      cd /var/www/html
      drush si -y --account-name=admin --account-mail=mrbagnall@icloud.com --site-mail=mrbagnall@icloud.com --account-pass=SailAway77 --site-name="Probo Drupal 9 Site Install"
      drush pm:enable -y admin_toolbar search_api search_api_solr module_filter
      chmod 755 /src/docroot/web/sites/default/settings.php
