image: proboci/ubuntu:20.04-php8.1

steps:
  - name: Copy Drupal 10 Files From Drupal.org
    plugin: Script
    script: |
      rm -rf /var/www/html
      cd $SRC_DIR
      composer create-project drupal/recommended-project:10.0.0-alpha2 docroot
      cd /src/docroot
      composer require drush/drush:11.x-dev drupal/admin_toolbar
      chmod -R 777 /src/docroot/web/sites/default

  - name: Set Up Database For Drupal 10
    plugin: Drupal
    drupalVersion: 10
    subDirectory: docroot/web

  - name: Run the Drupal 10 Site Installation
    plugin: Script
    script: |
      cd /var/www/html
      drush si -y --account-name=admin --account-mail=mrbagnall@icloud.com --site-mail=mrbagnall@icloud.com --account-pass=SailAway77 --site-name="Probo Drupal 10 Site Install"
      drush pm:enable -y admin_toolbar
      chmod 755 /src/docroot/web/sites/default/settings.php
