image: proboci/ubuntu:18.04-php7.2

steps:
  - name: Set PHP Version 8.1
    plugin: LAMPApp
    
  - name: Basic Information Page
    command: 'mv $SRC_DIR/src /var/www/html'

  - name: Update SOLR
    plugin: Script
    script: |
      service solr stop
      wget https://proofroom.s3.amazonaws.com/solr-8.11.1.tgz
      tar xzf solr-8.11.1.tgz solr-8.11.1/bin/install_solr_service.sh --strip-components=2
      ./install_solr_service.sh solr-8.11.1.tgz
      service solr start
      wget https://ftp.drupal.org/files/projects/search_api_solr-4.2.3.tar.gz
      rm -rf /opt/solr/search_api_solr
      tar xzf search_api_solr-4.2.3.tar.gz
      mv search_api_solr /opt/solr/.
      sudo -u solr -- /opt/solr/bin/solr create -c solr8 -d "/opt/solr/search_api_solr/jump-start/solr8/config-set"
