image: proboci/ubuntu:18.04-php8.0

steps:
  - name: Set up our LAMP Plugin 18.04
    plugin: LAMPApp
  - name: Basic Information Page
    command: 'mv $SRC_DIR/src /var/www/html'
  - name: Versionizer output
    command: versionizer
