image: proboci/ubuntu:22.04-php8.2-beta
steps:
  - name: PHP 8.2 - Beta Server Testing
    plugin: LAMPApp
    phpIniOptions:
      memory_limit: 1024M
  - name: Basic Information Page
    command: 'mv $SRC_DIR/src /var/www/html'
  - name: Versionizer output
    command: versionizer
    
