image: proboci/ubuntu:24.04-php8.1
steps:
  - name: Testing 22.04 - PHP 8.1
    plugin: LAMPApp
    phpIniOptions:
      memory_limit: 1024M
  - name: Basic Information Page
    command: 'mv $SRC_DIR/src /var/www/html'
  - name: Versionizer output
    command: versionizer
    
