image: proboci/ubuntu:20.04-php8.1

steps:
  - name: Install Drupal 9
    plugin: Script
    script: |
      rm -rf /var/www/html
      cd $SRC_DIR
      composer create-project drupal/recommended-project docroot
      cd /src/docroot
      composer require drush/drush drupal/admin_toolbar drupal/search_api drupal/search_api_solr mbagnall/gov-info
      cd /src/docroot/web/modules
      wget https://github.com/ElusiveMind/govinfo/archive/main.zip
      unzip main.zip
      cd /var/www
      chmod -R 777 /src/docroot/web/sites/default

  - name: Set Up Database For Drupal 9
    plugin: Drupal
    drupalVersion: 9
    subDirectory: docroot/web

