image: proboci/ubuntu:18.04-php8.0
steps:
  - name: Create A Base Backdrop Site
    plugin: Backdrop
    runInstall: true
    installArgs: --username=admin --password=Welcome12345 --email=mbagnall@zivtech.com --site-name="Backdrop Development"
    subDirectory: ''
