image: proboci/ubuntu:18.04-php7.1
steps:
  - name: Set up our LAMP Plugin
    plugin: LAMPApp
    phpIniOptions:
      memory_limit: 1024M
  - name: Basic Information Page
    command: 'mv $SRC_DIR/src /var/www/html'
  - name: Versionizer output
    command: versionizer
