image: proboci/alpine:php8.1

steps:
  - name: Set up our LAMP Plugin
    plugin: LAMPApp
    phpIniOptions:
      memory_limit: 512M
      max_execution_time: 300
    subDirectory: src
  - name: Versionizer output
    command: versionizer
    
