image: proboci/ubuntu:20.04-php8.1

steps:
  - name: Copy Drupal 9 Files From Drupal.org
    plugin: Script
    script: |
      rm -rf /var/www/html
      cd $SRC_DIR
      composer create-project drupal/recommended-project docroot
      cd /src/docroot
      composer require drush/drush drupal/admin_toolbar drupal/search_api drupal/search_api_solr mbagnall/gov-info
      cd /src/docroot/web/modules
      wget https://github.com/ElusiveMind/govinfo/archive/main.zip
      unzip main.zip
      chmod -R 777 /src/docroot/web/sites/default

  - name: Set Up Database For Drupal 9
    plugin: Drupal
    drupalVersion: 9
    subDirectory: docroot/web

  - name: Run the Drupal 9 Site Installation
    script: |
      cd /var/www/html
      drush si --account-name=admin --account-mail=mrbagnall@icloud.com --site-mail=mrbagnall@icloud.com --account-pass=SailAway77 --site-name="Probo Drupal 9 Site Install"
      chmod 755 /src/docroot/web/sites/default/settings.php
