image: proboci/ubuntu:20.04-php8.0
assets:
  - social.sql.gz

steps:
  - name: Import Database With Progress
    plugin: LAMPApp
    database: social.sql.gz
    databaseGzipped: true
    subDirectory: src